### PR TITLE
Add new WMI query 'WmiMonitorID' to reliably list connected monitors.

### PR DESCRIPTION
**Pull request by Geevo**
By leveraging the WmiMonitorID class, the goal is to address [Issue 50](https://github.com/Jinjinov/Hardware.Info/issues/50) and the fact there are known issues with the Win32_DesktopMonitor class, which often fails to accurately list or even name the connected monitors. 

This addition is to attempt to provide a more reliable and correct listing of connected monitors and their potential names.

However, it's important to note that the presence of accurate EDID information within the monitors themselves is required in obtaining reliable results.

https://learn.microsoft.com/en-us/windows/win32/wmicoreprov/wmimonitorid

 - Added a new 'GetMonitorExtendedList' method to query the WmiMonitorID class..

- Added new model 'MonitorExtended' to map the properties retrieved from the WmiMonitorID class, providing an alternative set of information without creating breaking changes to the existing 'Monitor' class.

- A new field variable named _managementScopeWmi to provide access to the root\wmi namespace.

- I made sure to keep the code consistent with the rest of the code base without causing any breaking changes.

I've tested on two different devices and the results below.

### Win32_DesktopMonitor (yes, just one single instance!)
Caption: Generic PnP Monitor
Description: Generic PnP Monitor
MonitorManufacturer: (Standard monitor types)
MonitorType: Generic PnP Monitor
Name: Generic PnP Monitor
PixelsPerXLogicalInch: 96
PixelsPerYLogicalInch: 96

### WmiMonitorID
1#
Active: True
ManufacturerName: BNQ
ProductCodeID: 78CE
SerialNumberID: 8CG016XXXXX _- (Real serial omitted)_
UserFriendlyName: BenQ GL2460
WeekOfManufacture: 51
YearOfManufacture: 2016

2#
Active: True
ManufacturerName: BNQ
ProductCodeID: 78CE
SerialNumberID: B1H030XXXXX _- (Real serial omitted)_
UserFriendlyName: BenQ GL2460
WeekOfManufacture: 3
YearOfManufacture: 2017

### Win32_DesktopMonitor
Caption: Generic PnP Monitor
Description: Generic PnP Monitor
MonitorManufacturer: (Standard monitor types)
MonitorType: Generic PnP Monitor
Name: Generic PnP Monitor
PixelsPerXLogicalInch: 144
PixelsPerYLogicalInch: 144

### WmiMonitorID
Active: True
ManufacturerName: CMN
ProductCodeID: 14FF
SerialNumberID: 0
UserFriendlyName: 
WeekOfManufacture: 47
YearOfManufacture: 2018

### CODE REVIEW

**Comment by Jinjinov** [comment]
Thank you so much for this, I see that was quite a bit of work.

I have some trouble connecting two monitors because of the combination of HDMI, DisplayPort, DVI outputs on my graphic card and I don't have the right video cable for the second monitor. I hope I can make it work tomorrow.

I see that you added `public class MonitorExtended` - but because `Hardware.Info` is cross platform, it must work the same on Windows, Linux and macOS (or at least I try to make it so). Unfortunately `MonitorExtended` and `GetMonitorExtendedList()` don't make sense on Linux and macOS, so these must be merged with `public class Monitor`. Can you do this? If not, no problem, I am really grateful for your contribution.

**Comment by Geevo** [comment]
You're right, in the context of Linux and Mac it doesn't make much sense.
My reasoning at the time was my computer with two attached monitors returns a single instance of `Win32_DesktopMonitor`, and inaccurate data at that too.

However, I think we can achieve the merge of `WmiMonitorID` into the `Monitor` class, we'll have to modify the original query and introduce two more to get the desired results.

First off we'll need to modify the original query to `Win32_PnPEntity` where `PNPClass='Monitor'`
This will provide us a `DeviceId` - We can use this to query both `Win32_DesktopMonitor` and `WmiMonitorID` their against their properties `PNPDeviceId` and `InstanceName` respectively 

I'll make the changes and update the pull request.

**Comment by Jinjinov** [comment]
While searching for a solution I came to the exact same conclusion, what you suggest seems optimal.

**Comment by Geevo** [comment]
Ok, that been updated. 
I hope you don't mind me using Linq on the subsequent queries, just to shorthand the unnecessarily need to loop through.

If either of the queries return null, the properties within the `Monitor` class are omitted and default values are used.

**Comment by Jinjinov** [comment]
I looked at it quickly and it seems it should work, thank you!

I am in the middle of solving `/Jinjinov/Usb.Events/issues/29` so I will merge your PR as soon as I finish there.

**Comment by Jinjinov** [comment]
It works great! Thank you so much!

https://github.com/Jinjinov/Hardware.Info/releases/tag/v11.1.1.0

**Pull request merged**
