### PR TITLE
Added CPU SLAT and SocketDesignation for Windows

### PR DESCRIPTION
**Pull request by AathifMahir**
Hi,

I have Added Some Essential Information's to CPU

Information's Added to CPUList:
SLAT
SocketDesignation

### CODE REVIEW

**Comment by Jinjinov** [comment]
make 2 different branches from your `master` branch:

https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository

**Comment by AathifMahir** [comment]
> make 2 different branches from your `AathifMahir:master` branch:
> 
> - `AathifMahir:cpu-branch`
> 
> - `AathifMahir:printer-branch`
> 
> 
> 
> https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository

I removed the changes for Printer Permission Issue, This pull requests only applies for CPU information

**Comment by Jinjinov** [comment]
When I click on `Files changed` in this pull request in github, I also see changes in the printer function:

https://github.com/Jinjinov/Hardware.Info/pull/15/files

**Comment by AathifMahir** [comment]
> When I click on `Files changed` in this pull request in github, I also see changes in the printer function:
> 
> 
> 
> https://github.com/Jinjinov/Hardware.Info/pull/15/files

Sorry, I must've push that change. Let me remove that

**Comment by Jinjinov** [comment]
please also rename:

    public Boolean SLAT { get; set; }

to 

    public Boolean SecondLevelAddressTranslationExtensions { get; set; }

because I want that all properties have the same names as in WMI (so that it is easier to find documentation)

**Comment by AathifMahir** [comment]
> please also rename:
> 
> 
> 
>     public Boolean SLAT { get; set; }
> 
> 
> 
> to 
> 
> 
> 
>     public Boolean SecondLevelAddressTranslationExtensions { get; set; }
> 
> 
> 
> because I want that all properties have the same names as in WMI (so that it is easier to find documentation)

Sure thing

**Comment by AathifMahir** [comment]
@Jinjinov Reverted the Print Fix and Renamed the SLAT

**Comment by Jinjinov** [comment]
Thank you!

**Pull request merged**
