### PR TITLE
Add Mockable interface

### PR DESCRIPTION
**Pull request by 240026763**
This pull request is in response to this Issue: https://github.com/Jinjinov/Hardware.Info/issues/10

Changes made:
-Renamed existing internal IHardwareInfo and inheriting classes to IHardwareInfoRetrieval
-Added interface IHardwareInfo for main public class HardwareInfo to allow it to be mocked.
-Added interfaces for each of the component classes since they have internal setters for each property
-No logic changes made

### CODE REVIEW

**Comment by Jinjinov** [comment]
I can see why you added interfaces for Component classes, but I am not sure if I wouldn't rather just make the setters public.

The only reason the setters are public is to prevent the user of the library accidently overwriting some data.

Do you think we can count on the common sense of library users to know what they are doing and just make the setters public?

**Comment by 240026763** [comment]
I thought the same about just making the setters public but then you are relying on the users to know not to edit or overwrite. I'm good with either way. It is easier to mock with the actual classes but only by a few keystrokes.

**Comment by Jinjinov** [comment]
The reason why public setters won't do much harm is that the data stored in those properties isn't used anywhere in this library, so I think even if someone were to change it, that wouldn't break anything in this library.

And since "hardware information" isn't something that beginner programmers are usually interested in, I suggest that we make the setters public :)

**Comment by 240026763** [comment]
All component classes now have public setters and the interfaces for them are gone.

**Comment by Jinjinov** [comment]
Thank you!

**Pull request merged**
