### PR TITLE
Addition to Hardware.Info to support Services/Daemons as well and more information for Hardware.Info

### PR DESCRIPTION
**Pull request by isenmann**
I have extend the Hardware.Info project with another project Service.Info, which give you the ability to read out all the services/daemons with its current state (Running, Stopped, etc.). Also you can start/stop/restart services/daemons on the system. Right now Windows and Linux is supported.

I also add more information to the Hardware.Info project, precisely add usage for each CPU core  and overall CPU usage and also add network throughput for each interface.

Updated the project to also netstandard2.1

### CODE REVIEW

**Comment by Jinjinov** [comment]
Hi, @isenmann 

Thank you for your pull request, but I can't accept it, because there are several problems:
- If you read my [CONTRIBUTING](https://github.com/Jinjinov/Hardware.Info/blob/master/CONTRIBUTING.md) you will see that I ask you to create an issue before submitting a pull request
- I need .NET Standard 2.0 because I am using this NuGet in a .NET Framework project, which doesn't support 2.1
- You completely changed my README. I won't merge that into my repository.
- You added Service.Info project. I can see that it can be very useful, but it doesn't belong in a NuGet package "Hardware.Info" because it violates separation of concerns.

I will close this pull request. If you make a new pull request with just CPU usage and network throughput, I will merge it.

Thank you for your interest in my project, I appreciate it!

**Comment by isenmann** [comment]
Hi @Jinjinov,

I have open another pull request with the changes you have requested. Only the CPU and network stuff is included now, also the project is back to netstandard2.0 and the README is restored. 

Thank you for the start of this project.

**Comment by isenmann** [comment]
Just to mention it here, I have started to add my service stuff into an own repository with the same structure like your library: https://github.com/isenmann/Service.Info 
It's also pushed as nuget package. Maybe you find it useful and want to try it ;-)

**Comment by Jinjinov** [comment]
That is great @isenmann !

If your code compiles with .NET Standard 2.0 you could perhaps use 2.0 because it is compatible with .NET Framework 4.8 and many programmers work on old .NET Framework projects (in big companies, for example) and can't migrate to .NET Core. More people will download your NuGet package :) But if you really need the C# language features of .NET Standard 2.1 then of course use 2.1

About macOS support - there are many companies that offer macOS in the cloud, for example, Amazon is offering macOS on AWS. I use virtual machines to test my code on Linux and macOS and it works well.

**Comment by isenmann** [comment]
Thanks for your feedback @Jinjinov! 
I will have a look to find a macOS somewhere in the cloud to test or implement the stuff for it.
About the netstandard2.0, I think I can change it or provide both target frameworks.

**Comment by isenmann** [comment]
@Jinjinov Just to let you know that Service.Info is now netstandard2.0. Not pushed as nuget package but will be done as soon as there are some more changes again.

**Pull request closed without merging**
